[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "wingertge <wingertge@gmail.com>",
]
categories = ["science"]
description = "Vision processing operations for burn tensors"
documentation = "https://docs.rs/burn-vision"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-vision"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-vision"
version.workspace = true


[features]
candle = ["burn-candle"]
cubecl-backend = ["cubecl", "burn-cubecl"]
default = ["ndarray", "cubecl-backend", "fusion"]
export-tests = ["burn-tensor-testgen"]
fusion = ["burn-fusion", "burn-cuda/fusion", "burn-wgpu/fusion"]
ndarray = ["burn-ndarray"]
tch = ["burn-tch"]

# Test features
test-cpu = ["export-tests"]
test-cuda = ["cubecl-backend", "export-tests"]
test-vulkan = ["burn-wgpu/vulkan", "cubecl-backend", "export-tests"]
test-wgpu = ["cubecl-backend", "export-tests"]

[dependencies]
burn-candle = { path = "../burn-candle", version = "0.17.0", optional = true }
burn-cubecl = { path = "../burn-cubecl", version = "0.17.0", optional = true }
burn-fusion = { path = "../burn-fusion", version = "0.17.0", optional = true }
burn-ir = { path = "../burn-ir", version = "0.17.0" }
burn-ndarray = { path = "../burn-ndarray", version = "0.17.0", optional = true }
burn-tch = { path = "../burn-tch", version = "0.17.0", optional = true }
burn-tensor = { path = "../burn-tensor", version = "0.17.0" }
burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.17.0", optional = true }
cubecl = { workspace = true, optional = true }
derive-new = { workspace = true }
ndarray = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
burn-cuda = { path = "../burn-cuda", version = "0.17.0", default-features = false }
burn-ndarray = { path = "../burn-ndarray", version = "0.17.0" }
burn-wgpu = { path = "../burn-wgpu", version = "0.17.0", default-features = false }
cubecl = { workspace = true }
