[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition.workspace = true
license.workspace = true
name = "image-classification-web"
publish = false
version.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = []
half_precision = []

[dependencies]
burn = { path = "../../burn", version = "0.12.0", default-features = false, features = [
    "ndarray",
] }
burn-wgpu = { path = "../../burn-wgpu", version = "0.12.0", default-features = false }
burn-candle = { path = "../../burn-candle", version = "0.12.0", default-features = false }

js-sys = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
wasm-logger = { workspace = true }
wasm-timer = { workspace = true }
console_error_panic_hook = { workspace = true }

[build-dependencies]
# Used to generate code from ONNX model
burn-import = { path = "../../burn-import" }

[profile.dev]
lto = "fat"

[profile.release]
lto = "fat"
