[package]
name = "train"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
log = { workspace = true }
console_error_panic_hook = "0.1.7"
console_log = { version = "1", features = ["color"] }
burn = { path = "../../../burn", default-features = false, features = [
  "autodiff",
  "ndarray-no-std",
  "train-minimal",
  "wasm-sync",
  "browser",
] }
serde = { workspace = true }
image = { version = "0.24.7", features = ["png"] }
