version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "tracel-ai/github-actions*"

  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "crates/burn"
      - "crates/burn-*"
      - "crates/burn-import/*-tests"
      - "examples/*"
      - "xtask"
    schedule:
      interval: "weekly"

