[package]
name = "burn-import-model-checks-silero-vad"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[features]
default = ["ndarray"]
ndarray = []
tch = []
wgpu = []
metal = []

[dependencies]
burn = { path = "../../../../crates/burn", features = [
    "ndarray",
    "tch",
    "wgpu",
    "metal",
] }

[build-dependencies]
burn-import = { path = "../../../burn-import" }
