[default]
extend-ignore-identifiers-re = ["ratatui", "NdArray*", "ND"]

[files]
extend-exclude = [
    "assets/ModuleSerialization.xml",
    "examples/image-classification-web/src/model/label.txt",
]
