[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
categories = []
description = "Core types and utilities shared across the Burn ecosystem."
edition.workspace = true
keywords = []
license.workspace = true
name = "burn-std"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-std"
documentation = "https://docs.rs/burn-std"
version.workspace = true

[lints]
workspace = true

[features]
default = ["std", "cubecl-common/default"]
std = ["cubecl-common/std", "num-traits/std"]
doc = ["default"]
cubecl = ["dep:cubecl"]
network = ["dep:indicatif", "dep:reqwest", "dep:tokio"]

[dependencies]
bytemuck = { workspace = true, features = ["extern_crate_alloc"] }
half = { workspace = true, features = ["bytemuck"] }
num-traits = { workspace = true }
serde = { workspace = true }

cubecl = { workspace = true, optional = true, default-features = false }
cubecl-common = { workspace = true, default-features = false, features = [
    "serde",
] }
cubecl-quant = { workspace = true }

# Network downloader
indicatif = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
dashmap = { workspace = true }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
