[package]
name = "burn-complex"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true


[features]
#candle = ["burn-candle"]
#cubecl-backend = ["cubecl", "burn-cubecl"]
#default = ["ndarray"]
#export-tests = ["burn-tensor-testgen"]
#fusion = ["burn-fusion", "burn-cuda/fusion", "burn-wgpu/fusion"]
#ndarray = ["burn-ndarray"]
std = ["burn-tensor/std"]
#tch = ["burn-tch"]

# Test features
# test-cpu = ["export-tests"]
# test-cuda = ["cubecl-backend", "export-tests"]
# test-wgpu = ["cubecl-backend", "export-tests"]
# test-vulkan = ["burn-wgpu/vulkan", "test-wgpu"]
# test-metal = ["burn-wgpu/metal", "test-wgpu"]

[dependencies]
bon = { workspace = true }
# burn-candle = { path = "../burn-candle", version = "0.19.0", optional = true }
# burn-cubecl = { path = "../burn-cubecl", version = "0.19.0", optional = true }
# burn-fusion = { path = "../burn-fusion", version = "0.19.0", optional = true }
# burn-ir = { path = "../burn-ir", version = "0.19.0" }
#burn-ndarray = { path = "../burn-ndarray", version = "0.19.0", optional = true }
# burn-tch = { path = "../burn-tch", version = "0.19.0", optional = true }
burn-tensor = { path = "../burn-tensor", version = "0.21.0-pre.1", default-features = false }
burn-std = { path = "../burn-std", version = "0.21.0-pre.1", default-features = false }
# burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.19.0", optional = true }
bytemuck = { workspace = true }
cubecl = { workspace = true, optional = true }
derive-new = { workspace = true }
half = { workspace = true }
macerator = { workspace = true }
ndarray = { workspace = true }
rand = { workspace = true, default-features = false }
#rand_distr = { workspace = true }
num-traits = { workspace = true }
num-complex = { version = "0.4.6" }
paste = { workspace = true }

[dev-dependencies]
#burn-cuda = { path = "../burn-cuda", version = "0.19.0", default-features = false }
burn-ndarray = { path = "../burn-ndarray", version = "0.21.0-pre.1" }
#burn-wgpu = { path = "../burn-wgpu", version = "0.19.0", default-features = false }
#cubecl = { workspace = true }

[lints]
workspace = true
