[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mnist-inference-web"
publish = false
version = "0.11.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["ndarray"]

ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { path = "../../burn", default-features = false }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = "0.3.65"

[dev-dependencies]
pollster = { workspace = true }
