[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
name = "text-classification"
publish = false
version = "0.6.0"

[features]
default = []

training = []
inference = []
f16 = []

[dependencies]
# Burn
burn = {path = "../../burn"}
burn-autodiff = {path = "../../burn-autodiff"}
burn-tch = {path = "../../burn-tch"}
burn-ndarray = {path = "../../burn-ndarray"}

# Tokenizer
tokenizers = {version = "0.13.2", default-features = false, features = [
  "onig",
  "http",
]}

# Utils
derive-new = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
