[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "text-classification"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = []
f16 = []
flex32 = []
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu"]
vulkan = ["burn/vulkan"]
remote = ["burn/remote"]
cuda = ["burn/cuda"]
rocm = ["burn/rocm"]
metal = ["burn/metal"]
ddp = ["burn/collective"]
router = ["burn/router", "burn/ndarray", "burn/rocm"]

[dependencies]
# Burn
burn = { path = "../../crates/burn", features = [
    "train",
    "tui",
    "sqlite-bundled",
    "metrics",
    "ndarray",
    "autotune",
    "fusion",
    "std",
], default-features = false }
log = { workspace = true }

# Tokenizer
tokenizers = { version = "0.22.1", default-features = false, features = [
    "onig",
    "http",
] }

# Utils
derive-new = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
