[package]
name = "burn-derive"
version = "0.2.3"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = """
Burn derive crate.
"""
repository = "https://github.com/nathanielsimard/burn/tree/main/burn-dataset"
readme="README.md"
keywords = []
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
