[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "Test generation crate for burn-tensor"
edition.workspace = true
license.workspace = true
name = "burn-tensor-testgen"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-tensor-testgen"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
