[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "louisfd <louisfd94@gmail.com>",
]
categories = ["science"]
description = "Cube Compute Language (CubeCL) is a subset of Rust that can be executed on accelerators for compute intensive tasks."
edition.workspace = true
keywords = []
license.workspace = true
name = "burn-cube"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/burn-cube"
version.workspace = true

[features]
default = ["tensor"]
std = []
template = []
tensor = ["burn-tensor"]
export_tests = []

[dependencies]
burn-compute = { path = "../burn-compute", version = "0.14.0", default-features = false }
burn-tensor = { path = "../burn-tensor", version = "0.14.0", default-features = false, optional = true }

bytemuck = { workspace = true }
half = { workspace = true, features = ["bytemuck"] }
serde = { workspace = true }
burn-cube-macros = { path = "../burn-cube-macros", version = "0.14.0" }
derive-new = { workspace = true }
num-traits = { workspace = true }

log = { workspace = true }

[dev-dependencies]
trybuild = "1"
