[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "ROCm HIP backend for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "rocm", "hip"]
license.workspace = true
name = "burn-rocm"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-rocm"
documentation = "https://docs.rs/burn-rocm"
version.workspace = true

[lints]
workspace = true

[features]
default = ["fusion", "burn-cubecl/default", "cubecl/default"]
fusion = ["burn-fusion", "burn-cubecl/fusion"]
autotune = ["burn-cubecl/autotune"]
autotune-checks = ["burn-cubecl/autotune-checks"]
doc = ["burn-cubecl/doc"]
std = ["burn-cubecl/std", "cubecl/std"]

[dependencies]
cubecl = { workspace = true, features = ["hip"] }
burn-cubecl = { path = "../burn-cubecl", version = "0.20.0-pre.1", default-features = true }
burn-tensor = { path = "../burn-tensor", version = "0.20.0-pre.1", features = [
    "cubecl-hip",
] }
burn-fusion = { path = "../burn-fusion", version = "0.20.0-pre.1", optional = true }

half = { workspace = true }
bytemuck = { workspace = true }

log = { workspace = true }
derive-new = { workspace = true }

[dev-dependencies]
burn-cubecl = { path = "../burn-cubecl", version = "0.20.0-pre.1", default-features = false, features = [
    "export_tests",
] }
paste = { workspace = true }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
