[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "guide"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/default", "burn/tui"]
vulkan = ["burn/vulkan"]

[dependencies]
burn = { path = "../../crates/burn", features = [
    "webgpu",
    "train",
    "vision",
], default-features = false }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
