[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "guide"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/std", "burn/tui", "burn/fusion"]

[dependencies]
# Disable autotune default for convolutions
burn = { path = "../../crates/burn", features = [
    "webgpu",
    "train",
    "vision",
    "vulkan",
    "autotune",
], default-features = false }

# Serialization
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
