[package]
authors = ["laggui <lagrange.guillaume.1@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "backend-dispatch"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
burn = { path = "../../crates/burn", default-features = false, features = [
    "dispatch",
    "cuda",
    "cpu",
    "autotune",
    "fusion",
    "autodiff",
] }
