[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "LibTorch backend for the Burn framework using the tch bindings."
documentation = "https://docs.rs/burn-tch"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "data"]
license.workspace = true
name = "burn-tch"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-tch"
version.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = ["burn-backend/std"]
doc = ["tch/doc-only"]
tracing = [
    "burn-backend/tracing",
]

[dependencies]
burn-backend = { path = "../burn-backend", version = "=0.21.0", default-features = false }

libc = { workspace = true }
log = { workspace = true }
tch = { workspace = true, features = ["download-libtorch"] }
torch-sys = { workspace = true }                             # for build script lib dir detection

[build-dependencies]
cc = "1.2.54"

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
