[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "LibTorch backend for the Burn framework using the tch bindings."
documentation = "https://docs.rs/burn-tch"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "data"]
license.workspace = true
name = "burn-tch"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-tch"
version.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = ["burn-tensor/std"]
doc = ["tch/doc-only"]

[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.20.0-pre.1", default-features = false }
burn-common = { path = "../burn-common", version = "0.20.0-pre.1", default-features = false }

half = { workspace = true, features = ["std"] }
libc = { workspace = true }
log = { workspace = true }
tch = { workspace = true, features = ["download-libtorch"] }
torch-sys = { workspace = true }                             # for build script lib dir detection


[dev-dependencies]
burn-autodiff = { path = "../burn-autodiff", version = "0.20.0-pre.1", default-features = false, features = [
    "export_tests",
] }
burn-tensor = { path = "../burn-tensor", version = "0.20.0-pre.1", default-features = false, features = [
    "export_tests",
] }
rand = { workspace = true, features = ["thread_rng"] }

[build-dependencies]
cc = "1.2.45"

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
