[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "RL crate for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license.workspace = true
name = "burn-rl"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-rl"
documentation = "https://docs.rs/burn-rl"
version.workspace = true

[dependencies]
burn-core = { path = "../burn-core", version = "=0.21.0-pre.1", features = [
    "dataset",
    "std",
], default-features = false }
burn-optim = { path = "../burn-optim", version = "=0.21.0-pre.1", features = [
    "std",
], default-features = false }

derive-new.workspace = true
log = { workspace = true }
rand.workspace = true

[dev-dependencies]
burn-ndarray = { path = "../burn-ndarray", version = "=0.21.0-pre.1" }

[lints]
workspace = true
