[package]
authors = ["laggui <lagrange.guillaume.1@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "custom-csv-dataset"
description = "Example implementation for loading a custom CSV dataset from disk"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/dataset"]
dataframe = ["dep:burn-dataset", "polars"]

[dependencies]
burn = {path = "../../crates/burn"}
burn-dataset = { path = "../../crates/burn-dataset", features = ["dataframe"], optional = true }

# File download
reqwest = {workspace = true, features = ["blocking"]}

# CSV parsing
csv = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

# Dataframe support (optional)
polars = {workspace = true, optional = true, features = ["csv", "temporal"]}
