[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "server"
publish = false
version.workspace = true

[features]
default = ["webgpu"]
cuda = ["burn/cuda", "cubecl/compilation-cache"]
webgpu = ["burn/webgpu"]
vulkan = ["burn/vulkan"]
ndarray = ["burn/ndarray"]

[dependencies]
cfg-if = { workspace = true }
burn = { path = "../../crates/burn", version = "0.18.0", features = ["server"] }
cubecl = { workspace = true }
