[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "custom-training-loop"
publish = false
version.workspace = true

[dependencies]
burn = {path = "../../crates/burn", features=["autodiff", "webgpu", "vision"]}
guide = {path = "../guide"}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

# Wgpu internal dependencies
derive-new = { workspace = true }
bytemuck = { workspace = true }
