[package]
name = "modern-lstm"
version = "0.1.0"
edition = "2021"

[features]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu"]
cuda = ["burn/cuda"]

[dependencies]
burn = { path = "../../crates/burn", features=["train"] }

# Random number generator
rand = { workspace = true }
rand_distr = { workspace = true }

# Serialization
serde = {workspace = true, features = ["std", "derive"]}

# Organise the results in dataframe
polars = { workspace = true }
