[package]
edition.workspace = true
name = "modern-lstm"
version = "0.4.1-rc.1"

[lints]
workspace = true

[features]
cuda = ["burn/cuda"]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { path = "../../crates/burn", features = ["train"] }

# Random number generator
rand = { workspace = true, features = ["thread_rng"] }
rand_distr = { workspace = true }

# Serialization
serde = { workspace = true, features = ["std", "derive"] }

# Organise the results in dataframe
planus = { workspace = true }
polars = { workspace = true }
