[package]
authors = [
    "Dilshod Tadjibaev (@antimora)",
    "Nathaniel Simard (@nathanielsimard)",
]
description = "Library for importing datamodels into the Burn framework"
edition.workspace = true
license.workspace = true
name = "burn-import"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-import"
documentation = "https://docs.rs/burn-import"
version.workspace = true

default-run = "onnx2burn"

[features]
default = ["onnx", "pytorch"]
onnx = ["burn-ndarray"]
pytorch = ["burn/record-item-custom-serde", "thiserror", "zip", "candle-core"]

[dependencies]
burn = { path = "../burn", version = "0.17.0", default-features = false, features = ["std"]}
burn-ndarray = { path = "../burn-ndarray", version = "0.17.0", default-features = false, optional = true }
onnx-ir = { path = "../onnx-ir", version = "0.17.0" }
candle-core = { workspace = true, optional = true }
derive-new = { workspace = true }
half = { workspace = true }
log = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
rust-format = { workspace = true, features = ["token_stream", "post_process"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
syn = { workspace = true, features = ["parsing"] }
thiserror = { workspace = true, optional = true }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true }
zip = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }

[package.metadata.docs.rs]
features = ["default"]
rustdoc-args = ["--cfg", "docsrs"]
