[package]
name = "text-generation"
version = "0.8.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
publish = false

[features]
default = []
f16 = []

[dependencies]
# Burn
burn = { path = "../../burn" }
burn-autodiff = { path = "../../burn-autodiff" }
burn-tch = { path = "../../burn-tch" }

# Tokenizer
tokenizers = { version = "0.13.3", default-features = false, features = [
    "onig",
    "http",
] }

# Utils
derive-new = { workspace = true}
serde = { workspace = true, features = ["std", "derive"] }
log = { workspace = true }
