[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "text-generation"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/dataset", "burn/sqlite-bundled"]
f16 = []

[dependencies]
# Burn
burn = {path = "../../crates/burn", features=["train", "tch"]}

# Tokenizer
tokenizers = {version = "0.22.1", default-features = false, features = [
  "onig",
  "http",
]}

# Utils
derive-new = {workspace = true}
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
