[package]
authors = [
  "nathanielsimard <nathaniel.simard.42@gmail.com>",
  "Dilshod Tadjibaev (@antimora)",
]
edition.workspace = true
license.workspace = true
name = "burn-no-std-tests"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-no-std-tests"
version.workspace = true

[dependencies]

# ** Please make sure all dependencies support no_std **

burn = { path = "../burn", version = "0.15.0", default-features = false }
burn-ndarray = { path = "../burn-ndarray", version = "0.15.0", default-features = false }

serde = { workspace = true }
