[package]
name = "dop_timer"
description = "Distributed operation timer utility."
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true
publish = false

[lints]
workspace = true

[features]
default = []
ndarray = ["burn/ndarray"]
cuda = ["burn/cuda"]
wgpu = ["burn/wgpu"]
metal = ["burn/metal"]

[dependencies]
clap = { workspace = true, features = ["derive"] }
burn = { path = "../../crates/burn", version = "=0.20.0-pre.6", features = ["collective", "tracing"] }

log = { workspace = true }
rand = { workspace = true }

tokio = { workspace = true, features = ["full", "tracing"] }
tracing = { workspace = true }
# todo: tracing-log
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true, features = ["trace"] }
opentelemetry_sdk = { workspace = true }
opentelemetry-aws = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["tracing", "grpc-tonic"] }
opentelemetry-stdout = "0.31.0"

