[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU backend for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "wgpu", "webgpu"]
license.workspace = true
name = "burn-wgpu"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-wgpu"
version.workspace = true

[features]
default = ["fusion", "burn-jit/default"]
fusion = ["burn-fusion", "burn-jit/fusion"]
autotune = ["burn-jit/autotune"]
template = ["burn-jit/template", "burn-cube/template"]
doc = ["burn-jit/doc"]
std = ["burn-jit/std"]

[dependencies]
burn-jit = { path = "../burn-jit", version = "0.14.0", default-features = false }
burn-compute = { path = "../burn-compute", version = "0.14.0", default-features = false }
burn-tensor = { path = "../burn-tensor", version = "0.14.0" }
burn-common = { path = "../burn-common", version = "0.14.0" }
burn-fusion = { path = "../burn-fusion", version = "0.14.0", optional = true }
burn-cube = { path = "../burn-cube", version = "0.14.0" }

bytemuck = { workspace = true }
wgpu = { workspace = true, features = ["fragile-send-sync-non-atomic-wasm"] }
pollster = { workspace = true }

log = { workspace = true }
futures-intrusive = { workspace = true }
derive-new = { workspace = true }
hashbrown = { workspace = true }

[dev-dependencies]
burn-jit = { path = "../burn-jit", version = "0.14.0", default-features = false, features = [
  "export_tests",
] }
burn-cube = { path = "../burn-cube", version = "0.14.0", features = [
  "export_tests",
] }
