[package]
name = "burn-tensor"
version = "0.3.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = """
This library provides multiple tensor implementations hidden behind
an easy to use API that supports reverse mode automatic differentiation.
"""
repository = "https://github.com/burn-rs/burn/tree/main/burn-tensor"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]
default = []
export_tests = ["burn-tensor-testgen"]

[dependencies]
burn-tensor-testgen = { version = "0.3.0", path = "../burn-tensor-testgen", optional = true }
num-traits = "0.2"
derive-new = "0.5"
rand = "0.8"
half = { version = "1.6", features = ["num-traits"] } # needs to be 1.6 to work with tch

# Autodiff
nanoid = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
