[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Generic backend that can be compiled just-in-time to any shader language target"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-jit"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-jit"
version.workspace = true

[features]
default = ["autotune", "std", "burn-compute/default", "fusion"]
std = []
doc = ["default"]
autotune = []
template = []
fusion = ["burn-fusion"]
export_tests = [
  "burn-tensor-testgen",
  "serial_test",
  "burn-autodiff/export_tests",
  "burn-tensor/export_tests",
  "burn-ndarray",
  "fusion",
]

[dependencies]
burn-common = { path = "../burn-common", version = "0.15.0" }
burn-tensor = { path = "../burn-tensor", version = "0.15.0" }
burn-fusion = { path = "../burn-fusion", version = "0.15.0", optional = true }

bytemuck = { workspace = true }
derive-new = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
spin = { workspace = true }
half = { workspace = true,  features = ["bytemuck"] }

# Template
serde = { workspace = true }
text_placeholder = { workspace = true, features = ["struct_context"] }

hashbrown = { workspace = true }
burn-compute = { path = "../burn-compute", version = "0.15.0", default-features = false, features = [
  "channel-mutex",
  "std",
] }
burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.15.0", optional = true }

# When exporting tests
serial_test = { workspace = true, optional = true }
burn-autodiff = { path = "../burn-autodiff", version = "0.15.0", default-features = false, optional = true }
burn-ndarray = { path = "../burn-ndarray", version = "0.15.0", optional = true }

[package.metadata.docs.rs]
features = ["doc"]
