[package]
name = "burn-tch"
version = "0.2.3"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = "Tch backend for burn"
repository = "https://github.com/burn-rs/burn/tree/main/burn-tch"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "data"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]
doc = ["tch/doc-only"]

[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.2.3", default-features = false }
rand = "0.8"
tch = { version = "0.8" }
lazy_static = "1.4"
half = { version = "1.6", features = ["num-traits"] } # needs to be 1.6 to work with tch

[dev-dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.2.3", default-features = false, features = ["export_tests"] }
