[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition.workspace = true
license = "MIT OR Apache-2.0"
name = "import-model-weights"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]

burn = { path = "../../crates/burn", features = [
    "ndarray",
    "dataset",
    "vision",
] }

burn-store = { path = "../../crates/burn-store", features = [
    "std",
    "pytorch",
    "safetensors",
    "burnpack",
], default-features = false }
