[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition.workspace = true
license = "MIT OR Apache-2.0"
name = "import-model-weights"
publish = false
version = "0.20.0-pre.1"

[lints]
workspace = true

[dependencies]

burn = { path = "../../crates/burn", features = [
    "ndarray",
    "dataset",
    "vision",
] }

burn-import = { path = "../../crates/burn-import", features = [
    "pytorch",
    "safetensors",
], default-features = false }
