[package]
authors = ["aasheeshsingh <aasheeshdtu@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "simple-regression"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/dataset", "burn/sqlite-bundled"]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu"]
remote = ["burn/remote"]

[dependencies]
burn = {path = "../../crates/burn", features=["train"]}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

# Displaying results
textplots = "0.8.7"
rgb = "0.8.51"