[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "onnx-inference"
publish = false
version = "0.11.0"

[features]
default = ["embedded-model"]

embedded-model = []

[dependencies]
burn = { path = "../../burn", features = ["ndarray", "dataset", "sqlite-bundled"] }
serde = { workspace = true }

[build-dependencies]
burn-import = { path = "../../burn-import" }
