[package]
name = "dqn-agent"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[features]
default = ["burn/tui"]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
remote = ["burn/remote"]
wgpu = ["burn/wgpu", "burn/default"]
metal = ["burn/metal", "burn/default"]
cuda = ["burn/cuda"]
vulkan = ["burn/vulkan", "burn/default"]
rocm = ["burn/rocm", "burn/default"]

[dependencies]
# Disable autotune default for now (convolutions not optimized)
burn = { path = "../../crates/burn", features = [
    "train",
    # "vision",
    "metrics",
    "std",
    "rl",
    # "fusion",
    "ndarray",
    # "autotune",
], default-features = false }
gym-rs = { version = "0.3.1", branch = "main", git = "https://github.com/MathisWellmann/gym-rs" }
rand.workspace = true
derive-new = { workspace = true }

[lints]
workspace = true
