[package]
name = "burn"
version = "0.3.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "BURN: Burn Unstoppable Rusty Neurons"
repository = "https://github.com/burn-rs/burn"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]

[dependencies]
burn-tensor = { version = "0.3.0", path = "../burn-tensor" }
burn-autodiff = { version = "0.3.0", path = "../burn-autodiff" }
burn-dataset = { version = "0.3.0", path = "../burn-dataset", default-features = false }
burn-derive = { version = "0.3.0", path = "../burn-derive" }

thiserror = "1.0"
num-traits = "0.2"
derive-new = "0.5"
rand = "0.8"

# Metrics
nvml-wrapper = "0.8"
textplots = "0.8"
rgb = "0.8"
terminal_size = "0.2"

# Console
indicatif = "0.17"
log4rs = "1.2"
log = "0.4"

# Serialize Deserialize
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"

# Parameter & Optimization
nanoid = "0.4"

[dev-dependencies]
burn-dataset = { version = "0.3.0", path = "../burn-dataset", features = ["fake"] }
burn-ndarray = { version = "0.3.0", path = "../burn-ndarray" }
