[package]
authors = [
  "Dilshod Tadjibaev (@antimora)",
  "Nathaniel Simard (@nathanielsimard)",
]
description = "Library for importing datamodels into the Burn framework"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "burn-import"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-import"

version = "0.9.0"

[features]
default = ["onnx"]
onnx = []

[dependencies]
burn = {path = "../burn", version = "0.9.0" }
burn-common = {path = "../burn-common", version = "0.9.0" }
burn-ndarray = {path = "../burn-ndarray", version = "0.9.0" }

bytemuck = {workspace = true}
derive-new = {workspace = true}
half = {workspace = true}
log = {workspace = true}
log4rs = {workspace = true}
proc-macro2 = {workspace = true}
protobuf = {version = "3.2", features = ["with-bytes"]}
quote = {workspace = true}
rust-format = {version = "0.3", features = ["token_stream", "post_process"]}
serde = {workspace = true}
serde_json = {workspace = true, features = ["std"]}
strum = {workspace = true}
strum_macros = {workspace = true}
syn = {workspace = true, features = ["parsing"]}

[build-dependencies]
protobuf-codegen = {workspace = true}

[dev-dependencies]
pretty_assertions = {workspace = true}
rstest = {workspace = true}
