[package]
name = "model"
version = "0.5.1"
edition = "2021"

[dependencies]
burn = { path = "../../../crates/burn" }
burn-import = { path = "../../../crates/burn-import", features = [
    "pytorch",
], default-features = false }

