[package]
name = "model"
version = "0.1.2"
edition = "2021"

[dependencies]
burn = { path = "../../../burn" }
burn-import = { path = "../../../burn-import", features = [
    "pytorch",
], default-features = false }

