[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = """
This library provides an easy to use dataset API with many manipulations
to easily create your ML data pipeline.
"""
edition = "2021"
keywords = ["deep-learning", "machine-learning", "data"]
license = "MIT"
name = "burn-dataset"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-dataset"
version = "0.6.0"

[features]
default = ["fake"]
fake = ["dep:fake"]

[dependencies]
dirs = {workspace = true}
fake = {workspace = true, optional = true}
rand = {workspace = true, features = ["std"]}
serde = {workspace = true, features = ["std", "derive"]}
serde_json = {workspace = true, features = ["std"]}
thiserror = {workspace = true}
derive-new = {workspace = true}

[dev-dependencies]
