[package]
name = "burn-dataset"
version = "0.1.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = """
This library provides an easy to use dataset API with many manipulations
to easily create your ML data pipeline.
"""
repository = "https://github.com/nathanielsimard/burn/tree/main/burn-dataset"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "data"]
categories = ["science"]
license = "MIT"
edition = "2021"

[features]
default = ["fake"]
fake = ["dep:fake"]

[dependencies]
dirs = "4.0"
rand = "0.8.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fake = { version = "2.5", optional = true }
thiserror = "1.0"

[dev-dependencies]
