[package]
name = "custom-learning-strategy"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
burn = {path = "../../crates/burn", default-features = false, features=["autodiff", "webgpu", "vision"]}
guide = {path = "../guide"}
derive-new = { workspace = true }
log = { workspace = true }