[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Provide optimizations that can be used with cubecl based backends."
documentation = "https://docs.rs/burn-cubecl-fusion"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-cubecl-fusion"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-cubecl-fusion"
version.workspace = true

[lints]
workspace = true

[features]
default = ["autotune", "std", "cubecl/default", "burn-fusion/default"]

autotune = []
autotune-checks = ["cubecl/autotune-checks"]
doc = ["default"]
std = ["cubecl/std", "burn-tensor/std", "burn-fusion/std"]

[dependencies]
burn-fusion = { path = "../burn-fusion", version = "=0.20.0-pre.5", default-features = false }
burn-ir = { path = "../burn-ir", version = "=0.20.0-pre.5", default-features = false }
burn-std = { path = "../burn-std", version = "=0.20.0-pre.5" }
burn-tensor = { path = "../burn-tensor", version = "=0.20.0-pre.5", default-features = false, features = [
    "cubecl",
] }
cubecl = { workspace = true }
cubek = { workspace = true, features = ["matmul", "reduce", "quantization"] }

derive-new = { workspace = true }
half = { workspace = true }
serde = { workspace = true }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
