[package]
name = "peft-mnist"
version = "0.20.0-pre.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
burn = { path = "../../crates/burn", features = ["train", "std", "dataset", "vision"] }
burn-peft = { path = "../../crates/burn-peft" }

[features]
default = ["ndarray"]
tch-gpu = ["burn/tch"]
tch-cpu = ["burn/tch"]
wgpu = ["burn/wgpu"]
wgpu-fusion = ["burn/wgpu", "burn/fusion"]
ndarray = ["burn/ndarray"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
cuda = ["burn/cuda", "burn/fusion"]
