name: Typos
on: pull_request

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Check spelling
        uses: crate-ci/typos@0863e64406a6d8f990ba7a1dd8f5a4683dd61194